### ISSUE TITLE
Readme incomplete

### ISSUE THREAD

**Issue by Pierinux** [romanpitak/PHP-REST-Client#4]
Thank you for your excellent work. In the Readme, you should probably specify in the example: 

 `$client = new RestClient\Client('https://raw.githubusercontent.com/romanpitak');` 

instead of: 

`$client = new Client('https://raw.githubusercontent.com/romanpitak');`

If you use composer to pull out and install dependencies, the simple `new Client()` call won't work. Thanks

**Comment by romanpitak** [comment]
I did consider that when I wrote it, but to keep the example small I chose to omit insignificant details such as the `vendor/autoload.php` inclusion and the namespace definition. 

Thank you very much for the suggestion though and thanks for caring about the open source software.
